{
 "title": "qBittorrent Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Time Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_downloaded_bytes"
    }
   ]
  },
  {
   "title": "All Time Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes"
    }
   ]
  },
  {
   "title": "Session Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_session_downloaded_bytes"
    }
   ]
  },
  {
   "title": "Session Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_session_uploaded_bytes"
    }
   ]
  },
  {
   "title": "Cumulative Download/Upload Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes",
     "legendFormat": "Download"
    },
    {
     "expr": "qbittorrent_global_upload_speed_bytes",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Global Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "qbittorrent_global_ratio" }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes"
    }
   ]
  },
  {
   "title": "Global Upload Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "qbittorrent_global_upload_speed_bytes"
    }
   ]
  },
  {
   "title": "qBittorrent Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "qbittorrent_app_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "qbittorrent_torrent_info" }
   ]
  },
  {
   "title": "Total Torrents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "qbittorrent_global_torrents" }
   ]
  },
  {
   "title": "Current Seeders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_seeders)"
    }
   ]
  },
  {
   "title": "Current Leechers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_leechers)"
    }
   ]
  },
  {
   "title": "States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "qbittorrent_torrent_states", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Amount Remaining Per Torrent",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "qbittorrent_torrent_amount_left_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Incomplete Torrent Progress",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "qbittorrent_torrent_progress < 1.0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Download Speed by Torrent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_torrent_download_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload Speed by Torrent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_torrent_upload_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}